name: Publish Docker Image

on:
  push:
    # Trigger on any git tag push
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/modern-minimal-portfolio:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/modern-minimal-portfolio:latest
          build-args: |
            APP_VERSION=${{ github.ref_name }}
